apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# images:
#   - name: docker.io/calico/node
#     newName: quay.io/cybozu/calico
#     newTag: 3.20.0.2
#   - name: docker.io/calico/typha
#     newName: quay.io/cybozu/calico
#     newTag: 3.20.0.2
resources:
  # - calico/upstream/calico-policy-only.yaml
  # - calico/rbac.yaml
  - cilium/global-policies/bmc-reverse-proxy.yaml
  - cilium/policies/ingress.yaml
  - cilium/policies/argocd-egress.yaml
  - cilium/policies/internet-egress.yaml
  - cilium/policies/customer-egress.yaml
  - cilium/policies/domestic-egress.yaml
  # - policies/kube-system.yaml
  - cilium/policies/logging.yaml
  - cilium/policies/monitoring.yaml
  - cilium/policies/teleport.yaml
  - cilium/global-policies/apiserver.yaml
  - cilium/global-policies/coil-nat.yaml
  - cilium/global-policies/controller-manager.yaml
  # - global-policies/egress-all-allow.yaml
  - cilium/global-policies/egress-backyard-deny.yaml
  - cilium/global-policies/egress-meows-runner.yaml
  # - global-policies/ingress-all-deny.yaml
  - cilium/global-policies/ingress-cluster-allow.yaml
  - cilium/global-policies/egress-cluster-allow.yaml
  # - global-policies/network-set.yaml
  - cilium/global-policies/ingress-node-dns-allow.yaml
  - cilium/global-policies/node-dns.yaml
  - cilium/global-policies/remote-node.yaml
  - cilium/global-policies/scheduler.yaml
# patchesStrategicMerge:
#   - calico/deployment.yaml
#   - calico/daemonset.yaml
#   - calico/crd.yaml
#   - calico/calico-kube-controllers.yaml
