apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moco
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ..
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://cybozu-go.github.io/moco
    chart: moco
    targetRevision: 0.1.0
    helm:
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: moco-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
