apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logging-promtail
  namespace: logging
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  template:
    spec:
      containers:
        - name: promtail
          image: "quay.io/cybozu/promtail"
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
            - "-config.expand-env=true"
          volumeMounts:
            - name: audit
              mountPath: /var/log/audit
              readOnly: true
            - name: journal
              mountPath: /var/log/journal
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: loki-promtail
          secret: null
        - hostPath:
            path: /var/log/audit
          name: audit
        - hostPath:
            path: /run/log/journal
          name: journal
      tolerations:
        - key: cke.cybozu.com/role
          operator: Equal
          value: storage
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: logging-promtail
  namespace: logging
---
