apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- includeCRDs: true
  name: rook-ceph
  releaseName: rook-release
  repo: https://charts.rook.io/release
  valuesFile: values.yaml
  version: v1.8.3
resources:
  - priorityclass.yaml
patches: # Strategic Merge Patch
- patch: |-
    - op: replace
      path: /spec/preserveUnknownFields
      value: false
  target:
    kind: CustomResourceDefinition
  # Delete manifests without CustomResourceDefinition and ClusterRole
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: ClusterRoleBinding
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: ConfigMap
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: Deployment
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: Role
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: RoleBinding
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: ServiceAccount
