$patch: delete
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-neco-guests
  namespace: teleport
---
$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-neco-guests
  namespace: teleport
