apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: egress-argocd
  namespace: argocd
spec:
  endpointSelector: {}
  egress:
  - toPorts:
    - ports:
      - port: "53"
        protocol: TCP
    - ports:
      - port: "53"
        protocol: UDP
    - ports:
      - port: "6443"
        protocol: TCP
    - ports:
      - port: "30128"
        protocol: TCP
