# Labels to be propagated to sub-namespaces.
labelKeys:
- team
- development

# Annotations to be propagated to sub-namespaces.
annotationKeys:
- metallb.universe.tf/address-pool

# List of GVK for namespace-scoped resources that can be propagated.
# Any namespace-scoped resource is allowed.
watches:
- group: rbac.authorization.k8s.io
  version: v1
  kind: Role
- group: rbac.authorization.k8s.io
  version: v1
  kind: RoleBinding
- version: v1
  kind: Secret
