apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-smallset
  namespace: monitoring
spec:
  extraArgs:
    promscrape.maxScrapeSize: 200MiB
  serviceScrapeNamespaceSelector:
    matchLabels:
      team: neco
  serviceScrapeSelector:
    matchLabels:
      smallset: "true"
  podScrapeNamespaceSelector:
    matchLabels:
      team: neco
  podScrapeSelector:
    matchLabels:
      smallset: "true"
  nodeScrapeNamespaceSelector:
    matchLabels:
      team: neco
  nodeScrapeSelector:
    matchLabels:
      smallset: "true"
  probeNamespaceSelector:
    matchLabels:
      team: neco
  probeSelector:
    matchLabels:
      smallset: "true"
  staticScrapeNamespaceSelector:
    matchLabels:
      team: neco
  staticScrapeSelector:
    matchLabels:
      smallset: "true"
  replicaCount: 1
  remoteWrite:
    - url: "http://vmsingle-vmsingle-smallset.monitoring.svc:8429/api/v1/write"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
            app.kubernetes.io/instance: vmsingle-smallset
            app.kubernetes.io/name: vmsingle
            managed-by: vm-operator
        topologyKey: kubernetes.io/hostname
