apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-largeset
  namespace: monitoring
spec:
  extraArgs:
    promscrape.maxScrapeSize: 200MiB
  serviceScrapeNamespaceSelector:
    matchLabels:
      team: neco
  serviceScrapeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  podScrapeNamespaceSelector:
    matchLabels:
      team: neco
  podScrapeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  nodeScrapeNamespaceSelector:
    matchLabels:
      team: neco
  nodeScrapeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  probeNamespaceSelector:
    matchLabels:
      team: neco
  probeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  staticScrapeNamespaceSelector:
    matchLabels:
      team: neco
  staticScrapeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  replicaCount: 3
  remoteWrite:
    - url: "http://vminsert-vmcluster-largeset.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
  podDisruptionBudget:
    minAvailable: 2
