apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert-smallset
  namespace: monitoring
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-vmsingle-smallset.monitoring.svc:8429"
  notifiers:
  - url: "http://vmalertmanager-vmalertmanager-smallset-0.vmalertmanager-vmalertmanager-smallset.monitoring.svc:9093"
  remoteWrite:
    url: "http://vmsingle-vmsingle-smallset.monitoring.svc:8429"
  evaluationInterval: "30s"
  ruleNamespaceSelector:
    matchLabels:
      team: neco
  ruleSelector:
    matchLabels:
      smallset: "true"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
            app.kubernetes.io/instance: vmsingle-smallset
            app.kubernetes.io/name: vmsingle
            managed-by: vm-operator
        topologyKey: kubernetes.io/hostname
