apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle-smallset
  namespace: monitoring
spec:
  retentionPeriod: "2"
  extraArgs:
    dedup.minScrapeInterval: 30s # should be equal to VMAgent's scrapeInterval (default 30s)
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Ti # we don't use pvc-autoresizer. see overlays/*/victoriametrics/vmsingle-smallset.yaml too.
    storageClassName: topolvm-provisioner
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: monitoring
              # rule1: vmsingle-smallset and vmalertmanager-smallset place in the same node.
              # rule2: avoid placing vmalertmanager-smallset and vmalertmanager-largest in the same node.
              # to satisfy rule1 and 2: vmsingle-smallset and vmalertmanager-largest are place in the different node.
              app.kubernetes.io/instance: vmalertmanager-largeset
              managed-by: vm-operator
