apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: psa-mutating-webhook-configuration
webhooks:
- name: baseline.mpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: pod-security.cybozu.com/policy
      operator: NotIn
      values:
      - privileged
      - traceable
      - rootable
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: psa-webhook-service
      namespace: kube-system
      path: /mutate-traceable
  failurePolicy: Fail
  name: traceable.mpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: pod-security.cybozu.com/policy
      operator: In
      values:
      - traceable
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: psa-webhook-service
      namespace: kube-system
      path: /mutate-rootable
  failurePolicy: Fail
  name: rootable.mpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: pod-security.cybozu.com/policy
      operator: In
      values:
      - rootable
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-system/psa-serving-cert
  name: psa-validating-webhook-configuration
webhooks:
- name: baseline.vpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: pod-security.cybozu.com/policy
      operator: NotIn
      values:
      - privileged
      - traceable
      - rootable
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: psa-webhook-service
      namespace: kube-system
      path: /validate-traceable
  failurePolicy: Fail
  name: traceable.vpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: pod-security.cybozu.com/policy
      operator: In
      values:
      - traceable
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: psa-webhook-service
      namespace: kube-system
      path: /validate-rootable
  failurePolicy: Fail
  name: rootable.vpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: pod-security.cybozu.com/policy
      operator: In
      values:
      - rootable
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
