apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kubernetes
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [default]
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
  endpoints:
  - port: https
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabelConfigs:
      - replacement: kubernetes-apiservers
        targetLabel: job
  - port: https
    scheme: http
    relabelConfigs:
      - replacement: kube-controller-manager
        targetLabel: job
      - sourceLabels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}:10252
        targetLabel: __address__
      - sourceLabels: [__address__]
        targetLabel: instance
  - port: https
    scheme: http
    relabelConfigs:
      - replacement: kube-scheduler
        targetLabel: job
      - sourceLabels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}:10251
        targetLabel: __address__
      - sourceLabels: [__address__]
        targetLabel: instance
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubernetes-nodes
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  scheme: https
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    - replacement: kubernetes-nodes
      targetLabel: job
    - action: labelmap
      regex: __meta_kubernetes_node_label_cke_cybozu_com_(.+)
      replacement: cke_${1}
    - action: labelmap
      regex: __meta_kubernetes_node_label_sabakan_cke_cybozu_com_(.+)
      replacement: sabakan_${1}
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443
    - sourceLabels: [__meta_kubernetes_node_name]
      targetLabel: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubernetes-cadvisor
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  path: /metrics
  port: "9110"
  relabelConfigs:
    - replacement: kubernetes-cadvisor
      targetLabel: job
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
  metricRelabelConfigs:
    - sourceLabels: [container_label_io_kubernetes_container_name]
      targetLabel: container
    - sourceLabels: [container_label_io_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [container_label_io_kubernetes_pod_namespace]
      targetLabel: namespace
    - action: labeldrop
      regex: container_label_io_kubernetes_.*
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kube-proxy
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  relabelConfigs:
    - replacement: kube-proxy
      targetLabel: job
    - sourceLabels: [__address__]
      action: replace
      regex: ([^:]+)(?::\d+)?
      replacement: ${1}:10249
      targetLabel: __address__
