apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - victoriametrics/vmsingle-smallset.yaml
  - victoriametrics/vmcluster-largeset.yaml
  - victoriametrics/rules/rook-scrape.yaml
configMapGenerator:
  - name: vmalertmanager
    behavior: merge
    files:
      - victoriametrics/env.template
