apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: egress-node-dns-allow
spec:
  endpointSelector: {}
  egress:
  - toEntities:
    - host
    - remote-node
    toPorts:
    - ports:
      - port: "53"
        protocol: TCP
    - ports:
      - port: "53"
        protocol: UDP
