apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: ceph-object-store
data:
  config: |
    [mgr]
    ; Suppress the folowing warning.
    ;
    ; ```
    ; health: HEALTH_WARN
    ;        1 pools have many more objects per pg than average
    ; ```
    mon_pg_warn_max_object_skew = 0
    [client]
    rgw_dynamic_resharding = false
    rgw enable ops log = true
    debug rgw = 20/20
    [global]
    mon_osd_down_out_subtree_limit = "root"
    ; If HEALTH_WARN appears, it should be investigated, but there is
    ; no requirement for slow ops. So this threshold was extended.
    osd_op_complaint_time = 300.0
