apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- includeCRDs: true
  name: rook-ceph
  namespace: ceph-ssd
  releaseName: rook-release
  repo: https://charts.rook.io/release
  valuesFile: values.yaml
  version: v1.8.3
nameSuffix: "-ssd"
patches: # Strategic Merge Patch
  # Delete manifests without ClusterRoleBinding
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: ClusterRole
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: ConfigMap
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: CustomResourceDefinition
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: Deployment
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: Role
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: RoleBinding
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: ServiceAccount
