apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: network-nat
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: domestic-egress
      k8s:app.kubernetes.io/component: egress
      k8s:app.kubernetes.io/instance: network-nat
      k8s:app.kubernetes.io/name: coil
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.cilium.k8s.namespace.labels.team: network
    toPorts:
    - ports:
      - port: "5555"
        protocol: UDP
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: monitoring
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
  egress:
  - toCIDR:
    # Switch network
    - 10.72.0.0/20
    - 10.76.0.0/20
    - 10.78.0.0/20
