apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-prometheus
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: vmagent
  egress:
  - toEntities:
    - host
    - remote-node
    toPorts:
    # etcd metrics
    - ports:
      - port: "2381"
        protocol: TCP
    # cilium-operator
    - ports:
      - port: "6942"
        protocol: TCP
    # metallb speaker
    - ports:
      - port: "7472"
        protocol: TCP
    # vault
    - ports:
      - port: "8200"
        protocol: TCP
    # cilium-agent
    - ports:
      - port: "9090"
        protocol: TCP
    # hubble
    - ports:
      - port: "9091"
        protocol: TCP
    # node_exporter
    - ports:
      - port: "9100"
        protocol: TCP
    # setup-hw
    - ports:
      - port: "9105"
        protocol: TCP
    # cadvisor
    - ports:
      - port: "9110"
        protocol: TCP
    # coild
    - ports:
      - port: "9384"
        protocol: TCP
    # coil-controller
    - ports:
      - port: "9386"
        protocol: TCP
    # sabakan
    - ports:
      - port: "10081"
        protocol: TCP
    # cke
    - ports:
      - port: "10180"
        protocol: TCP
    # kube-proxy
    - ports:
      - port: "10249"
        protocol: TCP
  - toCIDR:
    # Node network
    # CIDR based rule only applies to nodes outside the cluster including boot servers
    - 10.69.0.0/16
    toPorts:
    # etcd metrics
    - ports:
      - port: "2381"
        protocol: TCP
    # vault
    - ports:
      - port: "8200"
        protocol: TCP
    # node_exporter
    - ports:
      - port: "9100"
        protocol: TCP
    # setup-hw
    - ports:
      - port: "9105"
        protocol: TCP
    # sabakan
    - ports:
      - port: "10081"
        protocol: TCP
    # cke
    - ports:
      - port: "10180"
        protocol: TCP
    # kube-proxy
    - ports:
      - port: "10249"
        protocol: TCP
