apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator
spec:
  template:
    spec:
      containers:
        - name: grafana-operator
          args:
            - --grafana-image=quay.io/umezawatakeshi/grafana
            - --grafana-image-tag=v8.1.5-test1
            - --grafana-plugins-init-container-image=quay.io/cybozu/grafana_plugins_init
            - --grafana-plugins-init-container-tag=0.0.3.3
            - --scan-all
          env:
            - name: NO_PROXY
              value: 10.0.0.0/8
            - name: HTTP_PROXY
              value: http://squid.internet-egress.svc:3128
            - name: HTTPS_PROXY
              value: http://squid.internet-egress.svc:3128
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
