apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: egress-node-dns-allow
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  endpointSelector: {}
  egress:
    - toCIDR:
      - 10.69.0.0/16
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
        - ports:
            - port: "53"
              protocol: UDP
