{
 "title": "Coil",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "component", "query": "coil-controller,coild,egress" },
   {
    "name": "pool",
    "query": "label_values(coil_controller_max_blocks, pool)"
   }
  ]
 },
 "panels": [
  { "title": "Allocation Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocated Blocks (pool=${pool})",
   "type": "gauge",
   "description": "The number of unallocated address blocks from the pool",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "repeat": "pool",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "coil_controller_allocated_blocks{pool=\"${pool}\"}",
     "legendFormat": "A"
    },
    {
     "expr": "coil_controller_max_blocks{pool=\"${pool}\"} ",
     "legendFormat": "B"
    }
   ]
  },
  { "title": "coil-controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Reconciliation Time",
   "type": "graph",
   "description": "Length of time per reconciliation per controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"coil-controller\"}[5m])) by (le, controller))"
    }
   ]
  },
  { "title": "coild Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Successful CNI Calls",
   "type": "graph",
   "description": "The number of successful CNI calls.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"coild\", grpc_code=\"OK\"}[5m])) by (instance) * 300"
    }
   ]
  },
  {
   "title": "Failed CNI Calls",
   "type": "graph",
   "description": "The number of failed CNI calls.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"coild\", grpc_code!=\"OK\"}[5m])) by (instance) * 300"
    }
   ]
  },
  {
   "title": "Go/Process Telemetry (component=${component})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "component",
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Alloc Bytes (component=${component})",
     "type": "graph",
     "description": "Number of heap bytes in Go allocated and still in use.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"${component}\"}"
      }
     ]
    },
    {
     "title": "CPU time (component=${component})",
     "type": "graph",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"${component}\"}[1m])"
      }
     ]
    },
    {
     "title": "Goroutines (component=${component})",
     "type": "graph",
     "description": "Number of goroutines that currently exist.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"${component}\"}"
      }
     ]
    }
   ]
  }
 ]
}