{
 "title": "CSA Overview",
 "tags": [
  "ceph",
  "topolvm",
  "node"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Nodes state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CKE reboot queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(cke_reboot_queue_entries)" }
   ]
  },
  {
   "title": "Unhealthy nodes (kube)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_node_status_condition{status!=\"true\", condition=\"Ready\"}) by(node))"
    }
   ]
  },
  {
   "title": "Unhealthy nodes (sabakan)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "min(1 - sabakan_machine_status{status!~\"healthy|retired\"}) by(instance, machine_type, rack, role, serial, status) == 0"
    }
   ]
  },
  {
   "title": "Clock Skew Top 3+",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3,chrony_monitor_tracking_system_time_seconds)"
    }
   ]
  },
  { "title": "TopoLVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Fill rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(min(topolvm_volumegroup_available_bytes) by (instance, device_class)) / sum(max(topolvm_volumegroup_size_bytes) by (instance, device_class))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max(topolvm_volumegroup_size_bytes) by (instance, device_class)) - sum(min(topolvm_volumegroup_available_bytes) by (instance, device_class))"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(max(topolvm_volumegroup_size_bytes) by (instance, device_class))"
    }
   ]
  },
  {
   "title": "VG Fill Rate Top 3+",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, 1 - topolvm_volumegroup_available_bytes / topolvm_volumegroup_size_bytes)"
    }
   ]
  },
  { "title": "local-pv-provisioner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Fill rate (count based)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase!=\"Available\"} * on(persistentvolume) group_left kube_persistentvolume_info{storageclass=\"local-storage\"}) / sum(kube_persistentvolume_status_phase{} * on(persistentvolume) group_left kube_persistentvolume_info{storageclass=\"local-storage\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\"} * on(persistentvolume) group_left kube_persistentvolume_info{storageclass=\"local-storage\"}) by (phase)"
    }
   ]
  },
  {
   "title": "Bound",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Bound\"} * on(persistentvolume) group_left kube_persistentvolume_info{storageclass=\"local-storage\"}) by (phase)"
    }
   ]
  },
  {
   "title": "Released",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Released\"} * on(persistentvolume) group_left kube_persistentvolume_info{storageclass=\"local-storage\"}) by (phase)"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Failed\"} * on(persistentvolume) group_left kube_persistentvolume_info{storageclass=\"local-storage\"}) by (phase)"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Pending\"} * on(persistentvolume) group_left kube_persistentvolume_info{storageclass=\"local-storage\"}) by (phase)"
    }
   ]
  },
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "cluster" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without (instance) (ceph_health_status{namespace=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Cluster fill rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ceph_cluster_total_used_bytes{namespace=\"${cluster}\"})/max(ceph_cluster_total_bytes{namespace=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ceph_cluster_total_used_bytes{namespace=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ceph_cluster_total_bytes{namespace=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "OSD UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{namespace=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "OSD deployment available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"${cluster}\",deployment=~\"rook-ceph-osd-.*\"})"
    }
   ]
  },
  {
   "title": "One month forecast(usage)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(sum(ceph_cluster_total_used_bytes{namespace=\"${cluster}\"})[30d]) + sum(ceph_cluster_total_used_bytes{namespace=\"${cluster}\"})) / sum(ceph_cluster_total_bytes{namespace=\"${cluster}\"})"
    }
   ]
  },
  {
   "title": "Capacity to be expanded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(((3 * delta(sum(ceph_cluster_total_used_bytes{namespace=\"${cluster}\"})[30d]) + sum(ceph_cluster_total_used_bytes{namespace=\"${cluster}\"})) / 0.85) - sum(ceph_cluster_total_bytes{namespace=\"${cluster}\"}), 0)"
    }
   ]
  },
  {
   "title": "MON PV Fill Rate Top 3",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, kubelet_volume_stats_used_bytes{namespace=\"${cluster}\",persistentvolumeclaim=~\"rook-ceph-mon-.*\"}/kubelet_volume_stats_capacity_bytes{namespace=\"${cluster}\",persistentvolumeclaim=~\"rook-ceph-mon-.*\"})"
    }
   ]
  },
  {
   "title": "RGW response time(p90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, http_status, method) (rate(ceph_rgw_request_duration_seconds_bucket{namespace=\"${cluster}\"}[5m])))"
    }
   ]
  },
  {
   "title": "OSD PV Fill Rate Top 3+",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, ceph_osd_stat_bytes_used{namespace=\"${cluster}\"}/ceph_osd_stat_bytes{namespace=\"${cluster}\"})"
    }
   ]
  }
 ]
}