{
 "title": "Kubelet",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(kubelet_runtime_operations_total{job=\"kubernetes-nodes\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(up{job=\"kubernetes-nodes\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{job=\"kubernetes-nodes\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Container",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{job=\"kubernetes-nodes\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pod Volume Size",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{instance=~\"$instance\",job=\"kubernetes-nodes\"}",
     "legendFormat": "{{persistentvolumeclaim}} {{namespace}} available"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{instance=~\"$instance\",job=\"kubernetes-nodes\"}",
     "legendFormat": "{{persistentvolumeclaim}} {{namespace}} used"
    }
   ]
  },
  {
   "title": "Operation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_total{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_duration_seconds_bucket{job=\"kubernetes-nodes\",instance=~\"$instance\"}",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Pod Start Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_pod_start_duration_seconds_count{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "pod"
    },
    {
     "expr": "sum(rate(kubelet_pod_worker_start_duration_seconds_count{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "worker"
    }
   ]
  },
  {
   "title": "Pod Start Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "kubelet_pod_start_duration_seconds_bucket{job=\"kubernetes-nodes\",instance=~\"$instance\"}",
     "legendFormat": "pod {{quantile}}"
    },
    {
     "expr": "kubelet_pod_worker_start_duration_seconds_bucket{job=\"kubernetes-nodes\",instance=~\"$instance\"}",
     "legendFormat": "worker {{quantile}}"
    }
   ]
  },
  {
   "title": "Storage Operation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_operation_duration_seconds_count{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m])) by (operation_name,volume_plugin)",
     "legendFormat": "{{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(storage_operation_duration_seconds_bucket{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m])) by (operation_name,volume_plugin,le))",
     "legendFormat": "{{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Cgroup manager operation rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_cgroup_manager_duration_seconds_count{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Cgroup manager duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "kubelet_cgroup_manager_duration_seconds_bucket{job=\"kubernetes-nodes\",instance=~\"$instance\"}",
     "legendFormat": "{{operation_type}} {{quantile}}"
    }
   ]
  },
  {
   "title": "PLEG relist rate",
   "type": "graph",
   "description": "Pod lifecycle event generator",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_pleg_relist_interval_seconds_count{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "relist"
    }
   ]
  },
  {
   "title": "PLEG relist duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_interval_seconds_bucket{job=\"kubernetes-nodes\",instance=~\"$instance\"}",
     "legendFormat": "relist {{quantile}}"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kubernetes-nodes\", instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kubernetes-nodes\", instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kubernetes-nodes\", instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kubernetes-nodes\", instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(rest_client_request_duration_seconds_bucket{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m])) by (verb,url,le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kubernetes-nodes\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kubernetes-nodes\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kubernetes-nodes\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}