{
 "title": "Neco Admission",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantile", "query": "0.99,0.95,0.9" }
  ]
 },
 "panels": [
  {
   "title": "Controller Runtime Webhook Latency φ-quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"neco-admission\"}[1m])) by (le, webhook))"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"2..\", job=\"neco-admission\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"3..\", job=\"neco-admission\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"4..\", job=\"neco-admission\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"5..\", job=\"neco-admission\"}[5m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"<error>\", job=\"neco-admission\"}[5m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Rest Client Latency φ-quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(rest_client_request_duration_seconds_bucket{job=\"neco-admission\"}[1m])) by (le))"
    }
   ]
  }
 ]
}