{
 "title": "registry",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "registry",
    "label": "registry",
    "query": "label_values(registry_storage_action_seconds_bucket,registry)"
   }
  ]
 },
 "panels": [
  { "title": "Cache Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate per minute on $registry",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "repeat": "registry",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{type='Request',registry='$registry'}[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Cache hit ratio on $registry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "repeat": "registry",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{registry='$registry',type=\"Hit\"}[5m]))/sum(rate(registry_storage_cache_total{registry='$registry',type=\"Request\"}[5m]))*100",
     "legendFormat": "Hit"
    }
   ]
  },
  { "title": "Request Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Request duration 99th quantile on $registry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "repeat": "registry",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(registry_http_request_duration_seconds_bucket{registry='$registry'}[5m])) by (method,handler,le))"
    }
   ]
  },
  { "title": "Storage Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Storage action latency 99th quantile on $registry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "repeat": "registry",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(registry_storage_action_seconds_bucket{registry='$registry'}[5m])) by (action,le))"
    }
   ]
  },
  { "title": "Go/Process Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Heap Alloc Bytes",
   "type": "graph",
   "description": "Number of heap bytes in Go allocated and still in use.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job='registry'}",
     "legendFormat": "{{registry}}({{instance}})"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job='registry'}[1m])",
     "legendFormat": "{{registry}}({{instance}})"
    }
   ]
  },
  {
   "title": "Goroutines ",
   "type": "graph",
   "description": "Number of goroutines that currently exist.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines{job='registry'}", "legendFormat": "{{registry}}({{instance}})" }
   ]
  }
 ]
}