{
 "title": "Sabakan",
 "tags": [ "node" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sabakan_assets_bytes_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Count of healthy machines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(sabakan_machine_status{status=\"healthy\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Count of not healthy machines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(sabakan_machine_status{status!=\"healthy\"}) by (status,instance)) by (status)"
    }
   ]
  },
  {
   "title": "Total Bytes of Assets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sabakan_assets_bytes_total)"
    }
   ]
  },
  {
   "title": "Total Bytes of Images",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sabakan_images_bytes_total)"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(sabakan_machine_status{status=\"unhealthy\"})by(address, role, rack, serial) > 0"
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "avg(sabakan_machine_status{status=\"unreachable\"})by(address, role, rack, serial) > 0"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}