apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana-sandbox
  labels:
    app.kubernetes.io/name: grafana
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      containers:
        - name: grafana
          image: quay.io/cybozu/grafana:8.3.3.2
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: admin-user
                  name: grafana
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: admin-password
                  name: grafana
          ports:
            - containerPort: 3000
              name: grafana
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
          volumeMounts:
            - mountPath: /etc/grafana/grafana.ini
              name: config
              subPath: grafana.ini
            - mountPath: /etc/grafana/provisioning/datasources
              name: datasources-provider
            - mountPath: /var/lib/grafana
              name: grafana-data
            - mountPath: /var/log/grafana
              name: grafana-logs
      priorityClassName: node-bound
      securityContext:
        runAsUser: 10000
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: grafana
        - name: datasources-provider
          configMap:
            name: grafana-datasources-provider
            items:
              - key: providers.yaml
                path: providers.yaml
        - name: grafana-data
          emptyDir: {}
        - name: grafana-logs
          emptyDir: {}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana
  namespace: grafana-sandbox
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
