# permissions for end users to view subnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subnamespace-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - accurate.cybozu.com
  resources:
  - subnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - accurate.cybozu.com
  resources:
  - subnamespaces/status
  verbs:
  - get
