apiVersion: meows.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: neco-apps-runner
  namespace: meows-runner
spec:
  organization: cybozu-private
  replicas: 3
  maxRunnerPods: 25
  notification:
    slack:
      enable: true
      channel: "#kmdkuk-dev"
    extendDuration: "30m"
  workVolume:
    ephemeral:
      volumeClaimTemplate:
        spec:
          storageClassName: topolvm-flash1-xfs
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 15Gi
  template:
    metadata:
      annotations:
        egress.coil.cybozu.com/internet-egress: nat
    automountServiceAccountToken: false
    nodeSelector:
      reserved-for-meows: "true"
    tolerations:
      - key: neco/reserved_for_meows
        operator: Exists
    runnerContainer:
      image: quay.io/cybozu/meows-dctest-runner:0.7.0.4
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 15000m
          memory: 100Gi
        limits:
          cpu: 20000m
      volumeMounts:
          - name: scratch
            mountPath: /var/scratch
          - name: bird
            mountPath: /var/run/bird
          - name: modules
            mountPath: /lib/modules
          - name: dev
            mountPath: /dev
            readOnly: false
          - name: home
            mountPath: /home/actions
          - name: tools
            mountPath: /opt/hostedtoolcache
          - name: tmp
            mountPath: /tmp
    volumes:
        - name: bird
          emptyDir: {}
        - name: modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
        - name: scratch
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: topolvm-flash1-xfs
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 400Gi
        - name: home
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: topolvm-flash1-xfs
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 15Gi
        - name: tools
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: topolvm-flash1-xfs
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 15Gi
        - name: tmp
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: topolvm-flash1-xfs
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 15Gi
