apiVersion: meows.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: dctest-runner
  namespace: meows-runner
spec:
  replicas: 3
  slackAgent:
    serviceName: slack-agent.meows.svc
    channel: "#neco"
  setupCommand: ["/usr/local/bin/dctest-bootstrap"]
  template:
    metadata:
      annotations:
        egress.coil.cybozu.com/internet-egress: nat
    image: quay.io/cybozu/dctest-meows-runner:0.4.2.1
    securityContext:
      privileged: true
    env:
    - name: NECO_BRANCH
      value: "release"
    - name: NECO_APPS_BRANCH
      value: "release"
    - name: EXTEND_DURATION
      value: "30m"
    resources:
      requests:
        cpu: 15000m
        memory: 100Gi
      limits:
        cpu: 20000m
    workVolume:
      ephemeral:
        volumeClaimTemplate:
          spec:
            storageClassName: topolvm-flash1-xfs
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 15Gi
    volumeMounts:
        - name: scratch
          mountPath: /var/scratch
        - name: bird
          mountPath: /var/run/bird
        - name: modules
          mountPath: /lib/modules
        - name: dev
          mountPath: /dev
          readOnly: false
        - name: home
          mountPath: /home/actions
        - name: tools
          mountPath: /opt/hostedtoolcache
        - name: tmp
          mountPath: /tmp
        - name: secrets
          mountPath: /secrets
          readOnly: true
    volumes:
        - name: bird
          emptyDir: {}
        - name: modules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
        - name: scratch
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: topolvm-flash1-xfs
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 400Gi
        - name: home
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: topolvm-flash1-xfs
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 15Gi
        - name: tools
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: topolvm-flash1-xfs
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 15Gi
        - name: tmp
          ephemeral:
            volumeClaimTemplate:
              spec:
                storageClassName: topolvm-flash1-xfs
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 15Gi
        - name: secrets
          secret:
            secretName: clouddns
